### ISSUE TITLE
refactor: 배틀 관련 공통 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by NamJwong** [prgrms-web-devcourse/Team-6Jeans-Hype-FE#228]
## 📃 작업 내용

아래 페이지들의 공통 컴포넌트 설계를 다시 함
우발적 중복은 제거하고 각 컴포넌트들이 변경되는 이유를 기준으로 재설계함

<img width="812" alt="image" src="https://user-images.githubusercontent.com/73823388/223963771-b2eba10f-7159-4750-b10f-6fa803d71295.png">

### 적용 방식

각각의 컴포넌트를 바텀업으로 만든 후 페이지에 적용하려고 함

### TODO

- `components/battle/detail/BattleMusic`
  - [ ] BattleMusic 컴포넌트 만들기 `components/battle/detail/BattleMusic/index.tsx`
  - [ ] MovingBattleMusic 컴포넌트 만들기 `components/battle/detail/BattleMusic/Moving.tsx`
    - BattleMusic 컴포넌트에 moving 로직만 추가
  - [ ] FinishedBattleMusic 컴포넌트 만들기 `components/battle/detail/BattleMusic/Finished.tsx`

- `components/battle/detail/Battle` -> BattleMusic 컴포넌트 활용
  - [ ] Battle 컴포넌트 만들기 `components/battle/detail/Battle/index.tsx`
  - [ ] FinishedBattle 컴포넌트 만들기 `components/battle/detail/Battle/Finished.tsx`

- 이후 아직 미정

**Comment by NamJwong** [comment]
일단 1차로 완료해서 페이지에 적용시킴!
